/**
 * Write Proto files to disk
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import type { ProtoEnum, ProtoField, ProtoFile, ProtoMessage } from '../types.js';

export class ProtoWriter {
  /**
   * Write proto files to disk
   */
  async writeProtoFiles(
    protoFiles: Map<string, ProtoFile>,
    outputPath: string,
  ): Promise<void> {
    for (const [schemaName, protoFile] of protoFiles.entries()) {
      const filePath = this.getFilePath(outputPath, protoFile);

      // Ensure output directory exists
      await fs.mkdir(path.dirname(filePath), { recursive: true });

      // Generate proto content
      const content = this.generateProtoContent(protoFile);

      // Format the content (prettier doesn't support .proto, so we'll skip formatting)
      // In a real implementation, you might use a proto-specific formatter

      // Write to disk
      await fs.writeFile(filePath, content, 'utf-8');
      console.log(`Generated: ${filePath}`);
    }
  }

  /**
   * Generate proto file content
   */
  private generateProtoContent(protoFile: ProtoFile): string {
    const lines: string[] = [];

    // Auto-generated warning header
    lines.push(
      '// ============================================================================',
    );
    lines.push('// WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY');
    lines.push(
      '// ============================================================================',
    );
    lines.push('//');
    lines.push(
      '// This file was automatically generated by drizzle-proto-generator.',
    );
    lines.push(
      '// Any manual changes to this file will be overwritten on the next generation.',
    );
    lines.push('//');
    lines.push('// To modify the schema:');
    lines.push('// 1. Edit the source Drizzle schema files');
    lines.push('// 2. Re-run the proto generator: npx drizzle-proto-generator generate');
    lines.push('//');
    lines.push(
      '// ============================================================================',
    );
    lines.push('');

    // Syntax declaration
    lines.push(`syntax = "${protoFile.syntax}";`);
    lines.push('');

    // Package declaration
    lines.push(`package ${protoFile.package};`);
    lines.push('');

    // Imports
    if (protoFile.imports.length > 0) {
      for (const importPath of protoFile.imports) {
        lines.push(`import "${importPath}";`);
      }
      lines.push('');
    }

    // Enums
    for (const enumDef of protoFile.enums) {
      lines.push(...this.generateEnum(enumDef));
      lines.push('');
    }

    // Messages
    for (const message of protoFile.messages) {
      lines.push(...this.generateMessage(message));
      lines.push('');
    }

    return lines.join('\n').trim() + '\n';
  }

  /**
   * Generate enum definition
   */
  private generateEnum(enumDef: ProtoEnum): string[] {
    const lines: string[] = [];

    // Enum comment
    lines.push(`// ${enumDef.name}`);

    // Enum declaration
    lines.push(`enum ${enumDef.name} {`);

    // Enum values
    for (const value of enumDef.values) {
      lines.push(`  ${value.name} = ${value.number};`);
    }

    lines.push('}');

    return lines;
  }

  /**
   * Generate message definition
   */
  private generateMessage(message: ProtoMessage): string[] {
    const lines: string[] = [];

    // Message comment
    if (message.comment) {
      lines.push(`// ${message.comment}`);
    }

    // Message declaration
    lines.push(`message ${message.name} {`);

    // Fields
    for (const field of message.fields) {
      lines.push(...this.generateField(field));
    }

    lines.push('}');

    return lines;
  }

  /**
   * Generate field definition
   */
  private generateField(field: ProtoField): string[] {
    const lines: string[] = [];

    // Field comment
    if (field.comment) {
      lines.push(`  // ${field.comment}`);
    }

    // Build field declaration
    let declaration = '  ';

    // Add optional or repeated modifier
    if (field.repeated) {
      declaration += 'repeated ';
    } else if (field.optional) {
      declaration += 'optional ';
    }

    // Add type and name
    declaration += `${field.type} ${field.name} = ${field.number};`;

    lines.push(declaration);

    return lines;
  }

  /**
   * Get full file path following the pattern: <outputPath>/<packageName>/<versionNumber>/gen_types.proto
   */
  private getFilePath(outputPath: string, protoFile: ProtoFile): string {
    // Parse package name (e.g., "bueller.user.v1" -> ["bueller", "user", "v1"])
    // Or "bueller.common.v1" -> ["bueller", "common", "v1"]
    const packageParts = protoFile.package.split('.');

    // Extract base package name (everything except version)
    const versionPart = packageParts[packageParts.length - 1] ?? 'v1';
    const packageName = packageParts.slice(0, -1).join('.'); // "bueller.user" or "bueller.common"

    // Create directory structure: <outputPath>/<packageName>/<versionNumber>/
    const packageDir = packageName.replace(/\./g, '/'); // "bueller/user" or "bueller/common"
    const outputDir = path.join(outputPath, packageDir, versionPart);

    // Generate filename
    const fileName = 'gen_types.proto';

    return path.join(outputDir, fileName);
  }

  /**
   * Get file name from schema name (legacy method, kept for compatibility)
   */
  private getFileName(schemaName: string): string {
    if (schemaName === 'default') {
      return 'types.proto';
    }

    const cleanName = schemaName
      .replace(/_schema$/i, '')
      .replace(/_/g, '-')
      .toLowerCase();

    return `${cleanName}.proto`;
  }
}
